//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBookStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookStoreDataEntities : DbContext
    {
        public BookStoreDataEntities()
            : base("name=BookStoreDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Bill_Detail> Bill_Detail { get; set; }
        public virtual DbSet<Bill_Type> Bill_Type { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Book_Inventory> Book_Inventory { get; set; }
        public virtual DbSet<Book_Theme> Book_Theme { get; set; }
        public virtual DbSet<Book_Type> Book_Type { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Decentralization> Decentralizations { get; set; }
        public virtual DbSet<Discount_Code> Discount_Code { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Account> Employee_Account { get; set; }
        public virtual DbSet<Employee_Role> Employee_Role { get; set; }
        public virtual DbSet<Pay_Wage> Pay_Wage { get; set; }
        public virtual DbSet<Promotion_Type> Promotion_Type { get; set; }
        public virtual DbSet<Publishing_Company> Publishing_Company { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<Warehouse_Detail> Warehouse_Detail { get; set; }
    }
}
