//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_Detail
    {
        public int Detail_ID { get; set; }
        public int Warehouse_ID { get; set; }
        public int Book_ID { get; set; }
        public int Book_Count { get; set; }
        public double Book_Price { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
